[package]
name = "gtk_cursor_navigator"
version = "0.1.0"
edition = "2024"

[dependencies]
gdk4 = "0.9.6"
gdk4-sys = "0.9.6"
glib = "0.20.9"
gtk4 = "0.9.6"
gtk4-layer-shell = "0.5.0"
rand = "0.9.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.20"
